
import java.awt.Component;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Mr22xx
 */
public class tictactoeFrame extends javax.swing.JFrame {
    
    int turn = 2 ;
    int btnUsed [] = {0,0,0,0,0,0,0,0,0};
    int xWin [] = {0,0,0,0,0,0,0,0,0};
    int oWin [] = {0,0,0,0,0,0,0,0,0};
    private Component rootpane;
    
    int xwin (){
        if(xWin[0]==1 && xWin[1] ==1 && xWin[2] ==1){
            return 1;
        }
        else if(xWin[3]==1 && xWin[4] ==1 && xWin[5] ==1){
            return 1;
        }
        else if(xWin[6]==1 && xWin[7] ==1 && xWin[8] ==1){
            return 1;
        }
        else if(xWin[0]==1 && xWin[3] ==1 && xWin[6] ==1){
            return 1;
        }
        else if(xWin[1]==1 && xWin[4] ==1 && xWin[7] ==1){
            return 1;
        }
        else if(xWin[2]==1 && xWin[5] ==1 && xWin[8] ==1){
            return 1;
        }
        else if(xWin[2]==1 && xWin[4] ==1 && xWin[6] ==1){
            return 1;
        }
        else if(xWin[0]==1 && xWin[4] ==1 && xWin[8] ==1){
            return 1;
        }
                return 0;
    }
    
    int owin (){
        if(oWin[0]==1 && oWin[1] ==1 && oWin[2] ==1){
            return 1;
        }
        else if(oWin[3]==1 && oWin[4] ==1 && oWin[5] ==1){
            return 1;
        }
        else if(oWin[6]==1 && oWin[7] ==1 && oWin[8] ==1){
            return 1;
        }
        else if(oWin[0]==1 && oWin[3] ==1 && oWin[6] ==1){
            return 1;
        }
        else if(oWin[1]==1 && oWin[4] ==1 && oWin[7] ==1){
            return 1;
        }
        else if(oWin[2]==1 && oWin[5] ==1 && oWin[8] ==1){
            return 1;
        }
        else if(oWin[2]==1 && oWin[4] ==1 && oWin[6] ==1){
            return 1;
        }
        else if(oWin[0]==1 && oWin[4] ==1 && oWin[8] ==1){
            return 1;
        }
                return 0;
    }
    
    int draw(){
        if(xWin[0]==1 && oWin[1] ==1 && xWin[2] ==1 && xWin[3]==1 && oWin[4] ==1 && oWin[5] ==1 && oWin[6]==1 && xWin[7] ==1 && xWin[8] ==1){
            return 1;
    }
        else if (oWin[0] == 1 && xWin[1] == 1 && oWin [2] == 1 && oWin[3] == 1 && xWin[4] == 1 && xWin[5] == 1 && xWin[6] == 1 && oWin[7] == 1 && xWin[8] == 1){
            return 1;
        }
        else if (oWin[0] == 1 && xWin[1] == 1 && oWin [2] == 1 && xWin[3] == 1 && xWin[4] == 1 && oWin[5] == 1 && xWin[6] == 1 && oWin[7] == 1 && xWin[8] == 1){
            return 1;
        }
        else if (xWin[0] == 1 && oWin[1] == 1 && xWin [2] == 1 && xWin[3] == 1 && xWin[4] == 1 && oWin[5] == 1 && oWin[6] == 1 && xWin[7] == 1 && oWin[8] == 1){
            return 1;
        }
        else if (oWin[0] == 1 && xWin[1] == 1 && oWin [2] == 1 && xWin[3] == 1 && oWin[4] == 1 && xWin[5] == 1 && xWin[6] == 1 && oWin[7] == 1 && xWin[8] == 1){
            return 1;
        }
        else if (xWin[0] == 1 && oWin[1] == 1 && oWin [2] == 1 && oWin[3] == 1 && xWin[4] == 1 && xWin[5] == 1 && xWin[6] == 1 && xWin[7] == 1 && oWin[8] == 1){
            return 1;
        }
        else if (xWin[0] == 1 && oWin[1] == 1 && xWin [2] == 1 && xWin[3] == 1 && oWin[4] == 1 && xWin[5] == 1 && oWin[6] == 1 && xWin[7] == 1 && oWin[8] == 1){
            return 1;
        }
        else if (xWin[0] == 1 && oWin[1] == 1 && xWin [2] == 1 && oWin[3] == 1 && oWin[4] == 1 && xWin[5] == 1 && xWin[6] == 1 && xWin[7] == 1 && oWin[8] == 1){
            return 1;
        }
         else if (oWin[0] == 1 && xWin[1] == 1 && xWin [2] == 1 && xWin[3] == 1 && oWin[4] == 1 && oWin[5] == 1 && oWin[6] == 1 && xWin[7] == 1 && xWin[8] == 1){
            return 1;
        }
        
        return 0;
    }

    public tictactoeFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        restart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn1.setBackground(new java.awt.Color(0, 0, 0));
        btn1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(0, 0, 0));
        btn2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(0, 0, 0));
        btn3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(0, 0, 0));
        btn4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(0, 0, 0));
        btn5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn5.setForeground(new java.awt.Color(255, 255, 255));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(0, 0, 0));
        btn6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn6.setForeground(new java.awt.Color(255, 255, 255));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(0, 0, 0));
        btn7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn7.setForeground(new java.awt.Color(255, 255, 255));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(0, 0, 0));
        btn8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn8.setForeground(new java.awt.Color(255, 255, 255));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(0, 0, 0));
        btn9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn9.setForeground(new java.awt.Color(255, 255, 255));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        restart.setBackground(new java.awt.Color(255, 51, 51));
        restart.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        restart.setText("Restart");
        restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(restart, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(restart, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn7, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addComponent(btn8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        if(btnUsed [0] == 0){
            
        if (turn %2 == 0){
            
            turn ++;
            btn1.setText("X");
            btnUsed [0]=1;
            xWin[0] = 1;
            
            
            int resultX = xwin();
            int resultO = owin ();
            int seri = draw();
            
            if(resultX == 1){
                JOptionPane.showMessageDialog(rootpane, "Player X WON!!!");
            }
            else if(resultO == 1){
                JOptionPane.showMessageDialog(rootpane, "Player O WON!!!");
            }
            else if(seri == 1){
                JOptionPane.showMessageDialog(rootpane, "Game is Draw!!!");

            }
        }
        else{
            turn++;
            btn1.setText("O");
            btnUsed [0]=1;
            oWin[0] = 1;
            
            
             int resultX = xwin();
            int resultO = owin ();
            int seri = draw();
            
            if(resultX == 1){
                JOptionPane.showMessageDialog(rootpane, "Player X WON!!!");
            }
            else if(resultO == 1){
                JOptionPane.showMessageDialog(rootpane, "Player O WON!!!");
            }
             else if(seri == 1){
                JOptionPane.showMessageDialog(rootpane, "Game is Draw!!!");

            }
            

        }
        }
        else{
                JOptionPane.showMessageDialog(rootPane, "You just can do this once !!!");
    }//GEN-LAST:event_btn1ActionPerformed
        
        
        }

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
          if(btnUsed [1] == 0){
            
        if (turn %2 == 0){
            
            turn ++;
            btn2.setText("X");
            btnUsed [1]=1;
            xWin[1] = 1;
            int seri = draw();

            
            int resultX = xwin();
            int resultO = owin ();
            
            if(resultX == 1){
                JOptionPane.showMessageDialog(rootpane, "Player X WON!!!");
            }
            else if(resultO == 1){
                JOptionPane.showMessageDialog(rootpane, "Player O WON!!!");
            }
             else if(seri == 1){
                JOptionPane.showMessageDialog(rootpane, "Game is Draw!!!");

            }
        }
        else{
            turn++;
            btn2.setText("O");
            btnUsed [1]=1;
            oWin[1] = 1;
            
            
            int resultX = xwin();
            int resultO = owin ();
            int seri = draw ();
            
            if(resultX == 1){
                JOptionPane.showMessageDialog(rootpane, "Player X WON!!!");
            }
            else if(resultO == 1){
                JOptionPane.showMessageDialog(rootpane, "Player O WON!!!");
            }
             else if(seri == 1){
                JOptionPane.showMessageDialog(rootpane, "Game is Draw!!!");

            }
            

        }
        }
        else{
                JOptionPane.showMessageDialog(rootPane, "You just can do this once !!!");
    }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
          if(btnUsed [2] == 0){
            
        if (turn %2 == 0){
            
            turn ++;
            btn3.setText("X");
            btnUsed [2]=1;
            xWin[2] = 1;
          
            
            int resultX = xwin();
            int resultO = owin ();
            int seri = draw();
            
            if(resultX == 1){
                JOptionPane.showMessageDialog(rootpane, "Player X WON!!!");
            }
            else if(resultO == 1){
                JOptionPane.showMessageDialog(rootpane, "Player O WON!!!");
            }
             else if(seri == 1){
                JOptionPane.showMessageDialog(rootpane, "Game is Draw!!!");

            }
        }
        else{
            turn++;
            btn3.setText("O");
            btnUsed [2]=1;
            oWin[2] = 1;
           

            
            int resultX = xwin();
            int resultO = owin ();
            int seri = draw();
            
            if(resultX == 1){
                JOptionPane.showMessageDialog(rootpane, "Player X WON!!!");
            }
            else if(resultO == 1){
                JOptionPane.showMessageDialog(rootpane, "Player O WON!!!");
            }
             else if(seri == 1){
                JOptionPane.showMessageDialog(rootpane, "Game is Draw!!!");

            }
            

        }
        }
        else{
                JOptionPane.showMessageDialog(rootPane, "You just can do this once !!!");
    }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
          if(btnUsed [3] == 0){
            
        if (turn %2 == 0){
            
            turn ++;
            btn4.setText("X");
            btnUsed [3]=1;
            xWin[3] = 1;
            

            
            int resultX = xwin();
            int resultO = owin ();
            int seri = draw();
            
            if(resultX == 1){
                JOptionPane.showMessageDialog(rootpane, "Player X WON!!!");
            }
            else if(resultO == 1){
                JOptionPane.showMessageDialog(rootpane, "Player O WON!!!");
            }
             else if(seri == 1){
                JOptionPane.showMessageDialog(rootpane, "Game is Draw!!!");

            }
        }
        else{
            turn++;
            btn4.setText("O");
            btnUsed [3]=1;
            oWin[3] = 1;
            

            
             int resultX = xwin();
            int resultO = owin ();
            int seri = draw();
            
            if(resultX == 1){
                JOptionPane.showMessageDialog(rootpane, "Player X WON!!!");
            }
            else if(resultO == 1){
                JOptionPane.showMessageDialog(rootpane, "Player O WON!!!");
            }
             else if(seri == 1){
                JOptionPane.showMessageDialog(rootpane, "Game is Draw!!!");

            }
            

        }
        }
        else{
                JOptionPane.showMessageDialog(rootPane, "You just can do this once !!!");
    }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
          if(btnUsed [4] == 0){
            
        if (turn %2 == 0){
            
            turn ++;
            btn5.setText("X");
            btnUsed [4]=1;
            xWin[4] = 1;
            

            
            int resultX = xwin();
            int resultO = owin ();
            int seri = draw();
            
            if(resultX == 1){
                JOptionPane.showMessageDialog(rootpane, "Player X WON!!!");
            }
            else if(resultO == 1){
                JOptionPane.showMessageDialog(rootpane, "Player O WON!!!");
            }
             else if(seri == 1){
                JOptionPane.showMessageDialog(rootpane, "Game is Draw!!!");

            }
        }
        else{
            turn++;
            btn5.setText("O");
            btnUsed [4]=1;
            oWin[4] = 1;
            

            
             int resultX = xwin();
            int resultO = owin ();
            int seri = draw();
            
            if(resultX == 1){
                JOptionPane.showMessageDialog(rootpane, "Player X WON!!!");
            }
            else if(resultO == 1){
                JOptionPane.showMessageDialog(rootpane, "Player O WON!!!");
            }
             else if(seri == 1){
                JOptionPane.showMessageDialog(rootpane, "Game is Draw!!!");

            }
            

        }
        }
        else{
                JOptionPane.showMessageDialog(rootPane, "You just can do this once !!!");
    }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
          if(btnUsed [5] == 0){
            
        if (turn %2 == 0){
            
            turn ++;
            btn6.setText("X");
            btnUsed [5]=1;
            xWin[5] = 1;
            

            
            int resultX = xwin();
            int resultO = owin ();
            int seri = draw ();
            
            if(resultX == 1){
                JOptionPane.showMessageDialog(rootpane, "Player X WON!!!");
            }
            else if(resultO == 1){
                JOptionPane.showMessageDialog(rootpane, "Player O WON!!!");
            }
             else if(seri == 1){
                JOptionPane.showMessageDialog(rootpane, "Game is Draw!!!");

            }
        }
        else{
            turn++;
            btn6.setText("O");
            btnUsed [5]=1;
            oWin[5] = 1;
            

            
             int resultX = xwin();
            int resultO = owin ();
            int seri =  draw();
            
            if(resultX == 1){
                JOptionPane.showMessageDialog(rootpane, "Player X WON!!!");
            }
            else if(resultO == 1){
                JOptionPane.showMessageDialog(rootpane, "Player O WON!!!");
            }
             else if(seri == 1){
                JOptionPane.showMessageDialog(rootpane, "Game is Draw!!!");

            }
            

        }
        }
        else{
                JOptionPane.showMessageDialog(rootPane, "You just can do this once !!!");
    }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
          if(btnUsed [6] == 0){
            
        if (turn %2 == 0){
            
            turn ++;
            btn7.setText("X");
            btnUsed [6]=1;
            xWin[6] = 1;
            

            
            int resultX = xwin();
            int resultO = owin ();
            int seri = draw();
            
            if(resultX == 1){
                JOptionPane.showMessageDialog(rootpane, "Player X WON!!!");
            }
            else if(resultO == 1){
                JOptionPane.showMessageDialog(rootpane, "Player O WON!!!");
            }
             else if(seri == 1){
                JOptionPane.showMessageDialog(rootpane, "Game is Draw!!!");

            }
        }
        else{
            turn++;
            btn7.setText("O");
            btnUsed [6]=1;
            oWin[6] = 1;
            

            
             int resultX = xwin();
            int resultO = owin ();
            int seri = draw();
            
            if(resultX == 1){
                JOptionPane.showMessageDialog(rootpane, "Player X WON!!!");
            }
            else if(resultO == 1){
                JOptionPane.showMessageDialog(rootpane, "Player O WON!!!");
            } 
            else if(seri == 1){
                JOptionPane.showMessageDialog(rootpane, "Game is Draw!!!");

            }
            

        }
        }
        else{
                JOptionPane.showMessageDialog(rootPane, "You just can do this once !!!");
    }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
          if(btnUsed [7] == 0){
            
        if (turn %2 == 0){
            
            turn ++;
            btn8.setText("X");
            btnUsed [7]=1;
            xWin[7] = 1;
            

            
            int resultX = xwin();
            int resultO = owin ();
            int seri = draw();
            
            if(resultX == 1){
                JOptionPane.showMessageDialog(rootpane, "Player X WON!!!");
            }
            else if(resultO == 1){
                JOptionPane.showMessageDialog(rootpane, "Player O WON!!!");
            }
             else if(seri == 1){
                JOptionPane.showMessageDialog(rootpane, "Game is Draw!!!");

            }
        }
        else{
            turn++;
            btn8.setText("O");
            btnUsed [7]=1;
            oWin[7] = 1;
            

            
             int resultX = xwin();
            int resultO = owin ();
            int seri = draw();
            
            if(resultX == 1){
                JOptionPane.showMessageDialog(rootpane, "Player X WON!!!");
            }
            else if(resultO == 1){
                JOptionPane.showMessageDialog(rootpane, "Player O WON!!!");
            }
             else if(seri == 1){
                JOptionPane.showMessageDialog(rootpane, "Game is Draw!!!");

            }
            

        }
        }
        else{
                JOptionPane.showMessageDialog(rootPane, "You just can do this once !!!");
    }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
          if(btnUsed [8] == 0){
            
        if (turn %2 == 0){
            
            turn ++;
            btn9.setText("X");
            btnUsed [8]=1;
            xWin[8] = 1;
            

            
            int resultX = xwin();
            int resultO = owin ();
            int seri = draw();
            
            if(resultX == 1){
                JOptionPane.showMessageDialog(rootpane, "Player X WON!!!");
            }
            else if(resultO == 1){
                JOptionPane.showMessageDialog(rootpane, "Player O WON!!!");
            }
             else if(seri == 1){
                JOptionPane.showMessageDialog(rootpane, "Game is Draw!!!");

            }
        }
        else{
            turn++;
            btn9.setText("O");
            btnUsed [8]=1;
            oWin[8] = 1;
            

            
             int resultX = xwin();
            int resultO = owin ();
            int seri = draw();
            
            if(resultX == 1){
                JOptionPane.showMessageDialog(rootpane, "Player X WON!!!");
            }
            else if(resultO == 1){
                JOptionPane.showMessageDialog(rootpane, "Player O WON!!!");
            }
             else if(seri == 1){
                JOptionPane.showMessageDialog(rootpane, "Game is Draw!!!");

            }
            

        }
        }
        else{
                JOptionPane.showMessageDialog(rootPane, "You just can do this once !!!");
    }
    }//GEN-LAST:event_btn9ActionPerformed

    private void restartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartActionPerformed
        btn1.setText("");
        btn2.setText("");
        btn3.setText("");
        btn4.setText("");
        btn5.setText("");
        btn6.setText("");
        btn7.setText("");
        btn8.setText("");
        btn9.setText("");
        
        
        turn = 2;
        for(int i = 0 ; i<=8 ; i++){
            btnUsed [i] = 0;
        }
        
        for(int i = 0 ; i<=8 ; i++){
             xWin[i] = 0;
        }
        
        for(int i = 0 ; i<=8 ; i++){
            oWin [i] = 0;
        }
        

    }//GEN-LAST:event_restartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tictactoeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tictactoeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tictactoeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tictactoeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tictactoeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton restart;
    // End of variables declaration//GEN-END:variables
}
